language: go
go:
  - "1.15.x"
sudo: false
install:
  - GO111MODULE=on go install -v ./...
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - export GO111MODULE=on
  - make fmt
  - make lint
  - make unit-race
  - make unit-cover
  - make goveralls
