language: go
go:
  - 1.5.4
  - 1.6.1
sudo: false
before_install:
  - gotools=golang.org/x/tools
install:
  - go get -v github.com/Masterminds/glide
  - glide install
  - go get -v ./...
  - go get -v $gotools/cmd/cover
  - go get -v github.com/golang/lint/golint
  - go get -v github.com/davecgh/go-spew/spew
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./goclean.sh
